create table GPS_full (
assetId text,
country text,
created text,
direction int,
distfrom text,
district text,
distto text,
federalstate text,
forwardDir text,
isdirectionvalid text,
lastlatitude int,
lastlongitude int,
latitude int,
longitude int,
oid text,
poshint text,
providerId text,
status text,
timestamputc timestamp,
tmc_latitude text,
tmc_longitude text,
tmcsegmentid text,
town text,
vehicletype text,
velocity int
)
